### ISSUE TITLE
Ability to run the specs in parallel

### ISSUE THREAD

**Issue by glabtest** [roberts1000/rspec_n#31]
Hi

This is an awesome gem! Thanks for working on it.
Do you also intend to run the specs in parallel? Or are there plans to do it in near future?

Thanks
Ramya

**Comment by roberts1000** [comment]
Hi.  I'm glad you're finding the gem helpful!  We can definitely look into adding support for parallel specs.  You may be able to use them today if you pass an exact command via the `-c` option. 

I'll probably take a closer look in April/May (once Rails 6 is released), unless you want to submit a PR sooner.

**Comment by roberts1000** [comment]
I'm going to close this, but if someone has time to work on way to automatically detect when parallel vs single specs should be run, I'm happy to take a PR. Parallel specs can be run today by using the `-c` option and passing the parallel command you want to run.
