### ISSUE TITLE
Add support for a config file

### ISSUE THREAD

**Issue by noctivityinc** [roberts1000/rspec_n#53]
This is a fantastic tool, but rather opinionated on the startup command.

It would be great if we could create a `.rspec_n` or the like and set our commands.  For example, I find myself doing this:

`rspec_n 10 --no-file -s --order defined -c 'rm -rf tmp && bundle exec rspec`

if we had a `.rspec_n` config file, we could do things like:

```
--no_file
-s 
--order defined
-c 'rm -rf tmp && bundle exec rspec`
```

Or something like that.

**Comment by roberts1000** [comment]
Thank you for the feedback! I like the idea.  I'll put something together once I have some bandwidth.

**Comment by joe-sharp** [comment]
This one should be an easy addition for me to add. In the mean time a good alias would certainly be a good workaround.

**Comment by roberts1000** [comment]
Agreed.

**Comment by joe-sharp** [comment]
I have a WIP branch started for this issue. Hopefully will open a PR someday soon.

**Comment by dutgcom** [comment]
@roberts1000, I've created a PR for this feature I badly need in production, so it's here  - https://github.com/roberts1000/rspec_n/pull/92

Please take a look and let me know what do you think.
