### ISSUE TITLE
Add options for Output Files

### ISSUE THREAD

**Issue by joe-sharp** [roberts1000/rspec_n#55]
The largest need that presented itself when I began using rspec_n was a way to preserve the log files and additionally to send them to a central location. I opened a PR to add options to do either/both.
https://github.com/roberts1000/rspec_n/pull/54

I'd be happy to start working on the other couple issues here if you would like the assistance!

**Comment by roberts1000** [comment]
Hi @joe-sharp. Thanks for the PR. I'm going to put some time into the gem over the weekend. I'll take a look at your PR and add some feedback. I like the idea behind your issue/PR.

Thank you for the offer to help as well. It would be great to have some help!
