### ISSUE TITLE
Add rubocop_plus to the Gemfile

### ISSUE THREAD

**Issue by joe-sharp** [roberts1000/rspec_n#61]
Minor issue, but one I had figured out before and forgot to report. You have a missing dependency for development on your rubocop-plus gem. After running the bin/setup script I still cannot run rubocop inside the repository without installing the gem due to the inherit_gem directive in .rubocop.yml. Here is the resulting error: `Unable to find gem rubocop_plus; is the gem installed? Gem::MissingSpecError`

**Comment by roberts1000** [comment]
This should be fixed now. I published a version of rubocop_plus to rubygems so it should install fine. I'm going to re-purpose this issue to add rubocop_plus to the Gemfile.
